// Generated by github.com/lolopinto/ent/ent, DO NOT EDIT.

import { AssocEdgeInputOptions, Ent, ID, Viewer } from "@lolopinto/ent";
import {
  Action,
  Builder,
  Changeset,
  Orchestrator,
  WriteOperation,
  saveBuilder,
  saveBuilderX,
} from "@lolopinto/ent/action";
import {
  Answer,
  Question,
  QuestionComment,
  QuestionPrivateNote,
  User,
} from "src/ent/";
import { EdgeType, NodeType } from "src/ent/const";
import schema from "src/schema/question";

export interface QuestionInput {
  title?: string;
  questionBody?: string;
  answered?: boolean;
  authorID?: ID | Builder<User>;
}

export interface QuestionAction extends Action<Question> {
  getInput(): QuestionInput;
}

function randomNum(): string {
  return Math.random().toString(10).substring(2);
}

export class QuestionBuilder implements Builder<Question> {
  orchestrator: Orchestrator<Question>;
  readonly placeholderID: ID;
  readonly ent = Question;
  private input: QuestionInput;

  public constructor(
    public readonly viewer: Viewer,
    public readonly operation: WriteOperation,
    action: QuestionAction,
    public readonly existingEnt?: Question | undefined,
  ) {
    this.placeholderID = `$ent.idPlaceholderID$ ${randomNum()}-Question`;
    this.input = action.getInput();

    this.orchestrator = new Orchestrator({
      viewer: viewer,
      operation: this.operation,
      tableName: "questions",
      key: "id",
      loaderOptions: Question.loaderOptions(),
      builder: this,
      action: action,
      schema: schema,
      editedFields: () => {
        return this.getEditedFields.apply(this);
      },
    });
  }

  getInput(): QuestionInput {
    return this.input;
  }

  updateInput(input: QuestionInput) {
    // override input
    this.input = {
      ...this.input,
      ...input,
    };
  }

  // this gets the inputs that have been written for a given edgeType and operation
  // WriteOperation.Insert for adding an edge and WriteOperation.Delete for deleting an edge
  getEdgeInputData(edgeType: EdgeType, op: WriteOperation) {
    return this.orchestrator.getInputEdges(edgeType, op);
  }

  clearInputEdges(edgeType: EdgeType, op: WriteOperation, id?: ID) {
    this.orchestrator.clearInputEdges(edgeType, op, id);
  }
  addAnswer(...ids: ID[]): QuestionBuilder;
  addAnswer(...nodes: Answer[]): QuestionBuilder;
  addAnswer(...nodes: Builder<Answer>[]): QuestionBuilder;
  addAnswer(...nodes: ID[] | Answer[] | Builder<Answer>[]): QuestionBuilder {
    for (const node of nodes) {
      if (this.isBuilder(node)) {
        this.addAnswerID(node);
      } else if (typeof node === "object") {
        this.addAnswerID(node.id);
      } else {
        this.addAnswerID(node);
      }
    }
    return this;
  }

  addAnswerID(
    id: ID | Builder<Answer>,
    options?: AssocEdgeInputOptions,
  ): QuestionBuilder {
    this.orchestrator.addOutboundEdge(
      id,
      EdgeType.QuestionToAnswers,
      NodeType.Answer,
      options,
    );
    return this;
  }

  removeAnswer(...ids: ID[]): QuestionBuilder;
  removeAnswer(...nodes: Answer[]): QuestionBuilder;
  removeAnswer(...nodes: ID[] | Answer[]): QuestionBuilder {
    for (const node of nodes) {
      if (typeof node === "object") {
        this.orchestrator.removeOutboundEdge(
          node.id,
          EdgeType.QuestionToAnswers,
        );
      } else {
        this.orchestrator.removeOutboundEdge(node, EdgeType.QuestionToAnswers);
      }
    }
    return this;
  }

  addAuthor(...ids: ID[]): QuestionBuilder;
  addAuthor(...nodes: User[]): QuestionBuilder;
  addAuthor(...nodes: Builder<User>[]): QuestionBuilder;
  addAuthor(...nodes: ID[] | User[] | Builder<User>[]): QuestionBuilder {
    for (const node of nodes) {
      if (this.isBuilder(node)) {
        this.addAuthorID(node);
      } else if (typeof node === "object") {
        this.addAuthorID(node.id);
      } else {
        this.addAuthorID(node);
      }
    }
    return this;
  }

  addAuthorID(
    id: ID | Builder<User>,
    options?: AssocEdgeInputOptions,
  ): QuestionBuilder {
    this.orchestrator.addOutboundEdge(
      id,
      EdgeType.QuestionToAuthors,
      NodeType.User,
      options,
    );
    return this;
  }

  removeAuthor(...ids: ID[]): QuestionBuilder;
  removeAuthor(...nodes: User[]): QuestionBuilder;
  removeAuthor(...nodes: ID[] | User[]): QuestionBuilder {
    for (const node of nodes) {
      if (typeof node === "object") {
        this.orchestrator.removeOutboundEdge(
          node.id,
          EdgeType.QuestionToAuthors,
        );
      } else {
        this.orchestrator.removeOutboundEdge(node, EdgeType.QuestionToAuthors);
      }
    }
    return this;
  }

  addComment(...ids: ID[]): QuestionBuilder;
  addComment(...nodes: QuestionComment[]): QuestionBuilder;
  addComment(...nodes: Builder<QuestionComment>[]): QuestionBuilder;
  addComment(
    ...nodes: ID[] | QuestionComment[] | Builder<QuestionComment>[]
  ): QuestionBuilder {
    for (const node of nodes) {
      if (this.isBuilder(node)) {
        this.addCommentID(node);
      } else if (typeof node === "object") {
        this.addCommentID(node.id);
      } else {
        this.addCommentID(node);
      }
    }
    return this;
  }

  addCommentID(
    id: ID | Builder<QuestionComment>,
    options?: AssocEdgeInputOptions,
  ): QuestionBuilder {
    this.orchestrator.addOutboundEdge(
      id,
      EdgeType.QuestionToComments,
      NodeType.QuestionComment,
      options,
    );
    return this;
  }

  removeComment(...ids: ID[]): QuestionBuilder;
  removeComment(...nodes: QuestionComment[]): QuestionBuilder;
  removeComment(...nodes: ID[] | QuestionComment[]): QuestionBuilder {
    for (const node of nodes) {
      if (typeof node === "object") {
        this.orchestrator.removeOutboundEdge(
          node.id,
          EdgeType.QuestionToComments,
        );
      } else {
        this.orchestrator.removeOutboundEdge(node, EdgeType.QuestionToComments);
      }
    }
    return this;
  }

  addPrivateNote(...ids: ID[]): QuestionBuilder;
  addPrivateNote(...nodes: QuestionPrivateNote[]): QuestionBuilder;
  addPrivateNote(...nodes: Builder<QuestionPrivateNote>[]): QuestionBuilder;
  addPrivateNote(
    ...nodes: ID[] | QuestionPrivateNote[] | Builder<QuestionPrivateNote>[]
  ): QuestionBuilder {
    for (const node of nodes) {
      if (this.isBuilder(node)) {
        this.addPrivateNoteID(node);
      } else if (typeof node === "object") {
        this.addPrivateNoteID(node.id);
      } else {
        this.addPrivateNoteID(node);
      }
    }
    return this;
  }

  addPrivateNoteID(
    id: ID | Builder<QuestionPrivateNote>,
    options?: AssocEdgeInputOptions,
  ): QuestionBuilder {
    this.orchestrator.addOutboundEdge(
      id,
      EdgeType.QuestionToPrivateNotes,
      NodeType.QuestionPrivateNote,
      options,
    );
    return this;
  }

  removePrivateNote(...ids: ID[]): QuestionBuilder;
  removePrivateNote(...nodes: QuestionPrivateNote[]): QuestionBuilder;
  removePrivateNote(...nodes: ID[] | QuestionPrivateNote[]): QuestionBuilder {
    for (const node of nodes) {
      if (typeof node === "object") {
        this.orchestrator.removeOutboundEdge(
          node.id,
          EdgeType.QuestionToPrivateNotes,
        );
      } else {
        this.orchestrator.removeOutboundEdge(
          node,
          EdgeType.QuestionToPrivateNotes,
        );
      }
    }
    return this;
  }

  async build(): Promise<Changeset<Question>> {
    return this.orchestrator.build();
  }

  async valid(): Promise<boolean> {
    return this.orchestrator.valid();
  }

  async validX(): Promise<void> {
    return this.orchestrator.validX();
  }

  async save(): Promise<void> {
    await saveBuilder(this);
  }

  async saveX(): Promise<void> {
    await saveBuilderX(this);
  }

  async editedEnt(): Promise<Question | null> {
    return await this.orchestrator.editedEnt();
  }

  async editedEntX(): Promise<Question> {
    return await this.orchestrator.editedEntX();
  }

  private getEditedFields(): Map<string, any> {
    const fields = this.input;

    let result = new Map<string, any>();

    const addField = function (key: string, value: any) {
      if (value !== undefined) {
        result.set(key, value);
      }
    };
    addField("title", fields.title);
    addField("questionBody", fields.questionBody);
    addField("answered", fields.answered);
    addField("authorID", fields.authorID);
    if (fields.authorID) {
      this.orchestrator.addInboundEdge(
        fields.authorID,
        EdgeType.UserToAuthoredQuestions,
        NodeType.User,
      );
    }
    return result;
  }

  isBuilder(node: ID | Ent | Builder<Ent>): node is Builder<Ent> {
    return (node as Builder<Ent>).placeholderID !== undefined;
  }

  // get value of title. Retrieves it from the input if specified or takes it from existingEnt
  getNewTitleValue(): string | undefined {
    return this.input.title || this.existingEnt?.title;
  }

  // get value of questionBody. Retrieves it from the input if specified or takes it from existingEnt
  getNewQuestionBodyValue(): string | undefined {
    return this.input.questionBody || this.existingEnt?.questionBody;
  }

  // get value of answered. Retrieves it from the input if specified or takes it from existingEnt
  getNewAnsweredValue(): boolean | undefined {
    return this.input.answered || this.existingEnt?.answered;
  }

  // get value of authorID. Retrieves it from the input if specified or takes it from existingEnt
  getNewAuthorIDValue(): ID | Builder<User> | undefined {
    return this.input.authorID || this.existingEnt?.authorID;
  }
}
