# Code generated by github.com/lolopinto/ent/ent, DO NOT edit.

"""add column answered to table questions

Revision ID: 1640eb654c59
Revises: afe9c525d818
Create Date: 2021-06-23 09:00:23.858282+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '1640eb654c59'
down_revision = 'afe9c525d818'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column(
        'answered', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'answered')
    # ### end Alembic commands ###
