# Code generated by github.com/lolopinto/ent/ent, DO NOT edit.

"""drop constraint users_unique_email_address from users
drop column email_address
drop column password

Revision ID: 250874df8688
Revises: 15cf47c4068b
Create Date: 2021-08-15 23:35:41.476813+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '250874df8688'
down_revision = '15cf47c4068b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_unique_email_address', 'users', type_='unique')
    op.drop_column('users', 'email_address')
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.TEXT(),
                  autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('email_address', sa.TEXT(),
                  autoincrement=False, nullable=False))
    op.create_unique_constraint(
        'users_unique_email_address', 'users', ['email_address'])
    # ### end Alembic commands ###
