# Code generated by github.com/lolopinto/ent/ent, DO NOT edit.

"""add enum vote_type
add question_vote_voters_edges table
add index question_vote_voters_edges_time_idx to question_vote_voters_edges
add question_votes table
add question_votes_edges table
add index question_votes_edges_time_idx to question_votes_edges
add user_questions_voted_edges table
add index user_questions_voted_edges_time_idx to user_questions_voted_edges
add edges QuestionToVotesEdge, QuestionVoteToVotersEdge, UserToQuestionsVotedEdge, UserToVoterToQuestionsVotedEdge

Revision ID: 3c8d0f4ede92
Revises: c7acbd27509c
Create Date: 2021-08-11 21:24:18.842768+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3c8d0f4ede92'
down_revision = 'c7acbd27509c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_enum_type('vote_type', ['up', 'down'])
    op.create_table('question_vote_voters_edges',
                    sa.Column('id1', postgresql.UUID(), nullable=False),
                    sa.Column('id1_type', sa.Text(), nullable=False),
                    sa.Column('edge_type', postgresql.UUID(), nullable=False),
                    sa.Column('id2', postgresql.UUID(), nullable=False),
                    sa.Column('id2_type', sa.Text(), nullable=False),
                    sa.Column('time', sa.TIMESTAMP(), nullable=False),
                    sa.Column('data', sa.Text(), nullable=True),
                    sa.PrimaryKeyConstraint(
                        'id1', 'edge_type', 'id2', name='question_vote_voters_edges_id1_edge_type_id2_pkey')
                    )
    op.create_index('question_vote_voters_edges_time_idx',
                    'question_vote_voters_edges', ['time'], unique=False)
    op.create_table('question_votes',
                    sa.Column('id', postgresql.UUID(), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
                    sa.Column('vote_type', postgresql.ENUM('up', 'down',
                                                           name='vote_type', create_type=False), nullable=False),
                    sa.Column('question_id', postgresql.UUID(),
                              nullable=False),
                    sa.Column('user_id', postgresql.UUID(), nullable=False),
                    sa.PrimaryKeyConstraint(
                        'id', name='question_votes_id_pkey')
                    )
    op.create_table('question_votes_edges',
                    sa.Column('id1', postgresql.UUID(), nullable=False),
                    sa.Column('id1_type', sa.Text(), nullable=False),
                    sa.Column('edge_type', postgresql.UUID(), nullable=False),
                    sa.Column('id2', postgresql.UUID(), nullable=False),
                    sa.Column('id2_type', sa.Text(), nullable=False),
                    sa.Column('time', sa.TIMESTAMP(), nullable=False),
                    sa.Column('data', sa.Text(), nullable=True),
                    sa.PrimaryKeyConstraint(
                        'id1', 'edge_type', 'id2', name='question_votes_edges_id1_edge_type_id2_pkey')
                    )
    op.create_index('question_votes_edges_time_idx',
                    'question_votes_edges', ['time'], unique=False)
    op.create_table('user_questions_voted_edges',
                    sa.Column('id1', postgresql.UUID(), nullable=False),
                    sa.Column('id1_type', sa.Text(), nullable=False),
                    sa.Column('edge_type', postgresql.UUID(), nullable=False),
                    sa.Column('id2', postgresql.UUID(), nullable=False),
                    sa.Column('id2_type', sa.Text(), nullable=False),
                    sa.Column('time', sa.TIMESTAMP(), nullable=False),
                    sa.Column('data', sa.Text(), nullable=True),
                    sa.PrimaryKeyConstraint(
                        'id1', 'edge_type', 'id2', name='user_questions_voted_edges_id1_edge_type_id2_pkey')
                    )
    op.create_index('user_questions_voted_edges_time_idx',
                    'user_questions_voted_edges', ['time'], unique=False)
    op.add_edges([
        {'edge_name': 'QuestionToVotesEdge', 'edge_type': '67432296-9c50-4b5b-afe0-67d28c6e7776',
            'edge_table': 'question_votes_edges', 'symmetric_edge': False, 'inverse_edge_type': None},
        {'edge_name': 'QuestionVoteToVotersEdge', 'edge_type': 'ee449750-58df-4a33-a692-d8bf90e70a9d',
            'edge_table': 'question_vote_voters_edges', 'symmetric_edge': False, 'inverse_edge_type': 'f0d2fac2-6682-4150-aa90-b42749eae9d0'},
        {'edge_name': 'UserToQuestionsVotedEdge', 'edge_type': '92e68df1-d754-43dd-8e0d-6016f6caaba9',
            'edge_table': 'user_questions_voted_edges', 'symmetric_edge': False, 'inverse_edge_type': None},
        {'edge_name': 'UserToVoterToQuestionsVotedEdge', 'edge_type': 'f0d2fac2-6682-4150-aa90-b42749eae9d0',
            'edge_table': 'question_vote_voters_edges', 'symmetric_edge': False, 'inverse_edge_type': 'ee449750-58df-4a33-a692-d8bf90e70a9d'},
    ])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.remove_edges([
        {'edge_name': 'QuestionToVotesEdge', 'edge_type': '67432296-9c50-4b5b-afe0-67d28c6e7776',
            'edge_table': 'question_votes_edges', 'symmetric_edge': False, 'inverse_edge_type': None},
        {'edge_name': 'QuestionVoteToVotersEdge', 'edge_type': 'ee449750-58df-4a33-a692-d8bf90e70a9d',
            'edge_table': 'question_vote_voters_edges', 'symmetric_edge': False, 'inverse_edge_type': 'f0d2fac2-6682-4150-aa90-b42749eae9d0'},
        {'edge_name': 'UserToQuestionsVotedEdge', 'edge_type': '92e68df1-d754-43dd-8e0d-6016f6caaba9',
            'edge_table': 'user_questions_voted_edges', 'symmetric_edge': False, 'inverse_edge_type': None},
        {'edge_name': 'UserToVoterToQuestionsVotedEdge', 'edge_type': 'f0d2fac2-6682-4150-aa90-b42749eae9d0',
            'edge_table': 'question_vote_voters_edges', 'symmetric_edge': False, 'inverse_edge_type': 'ee449750-58df-4a33-a692-d8bf90e70a9d'},
    ])

    op.drop_index('user_questions_voted_edges_time_idx',
                  table_name='user_questions_voted_edges')
    op.drop_table('user_questions_voted_edges')
    op.drop_index('question_votes_edges_time_idx',
                  table_name='question_votes_edges')
    op.drop_table('question_votes_edges')
    op.drop_table('question_votes')
    op.drop_index('question_vote_voters_edges_time_idx',
                  table_name='question_vote_voters_edges')
    op.drop_table('question_vote_voters_edges')
    op.drop_enum_type('vote_type', ['up', 'down'])
    # ### end Alembic commands ###
