# Code generated by github.com/lolopinto/ent/ent, DO NOT edit.

"""add user_saved_authentication_details_edges table
add index user_saved_authentication_details_edges_time_idx to user_saved_authentication_details_edges
add column user_id to table user_authentications
add edge UserToSavedAuthenticationDetailsEdge

Revision ID: 5d35440812f8
Revises: ab645d2bc5bf
Create Date: 2021-08-15 21:30:30.283189+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5d35440812f8'
down_revision = 'ab645d2bc5bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_saved_authentication_details_edges',
                    sa.Column('id1', postgresql.UUID(), nullable=False),
                    sa.Column('id1_type', sa.Text(), nullable=False),
                    sa.Column('edge_type', postgresql.UUID(), nullable=False),
                    sa.Column('id2', postgresql.UUID(), nullable=False),
                    sa.Column('id2_type', sa.Text(), nullable=False),
                    sa.Column('time', sa.TIMESTAMP(), nullable=False),
                    sa.Column('data', sa.Text(), nullable=True),
                    sa.PrimaryKeyConstraint(
                        'id1', 'edge_type', 'id2', name='user_saved_authentication_details_edges_id1_edge_type_id2_pkey')
                    )
    op.create_index('user_saved_authentication_details_edges_time_idx',
                    'user_saved_authentication_details_edges', ['time'], unique=False)
    op.add_column('user_authentications', sa.Column(
        'user_id', postgresql.UUID(), nullable=False))
    op.add_edges([
        {'edge_name': 'UserToSavedAuthenticationDetailsEdge', 'edge_type': '2049f992-3325-4323-9875-9ee53bafff49',
            'edge_table': 'user_saved_authentication_details_edges', 'symmetric_edge': False, 'inverse_edge_type': None},
    ])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.remove_edges([
        {'edge_name': 'UserToSavedAuthenticationDetailsEdge', 'edge_type': '2049f992-3325-4323-9875-9ee53bafff49',
            'edge_table': 'user_saved_authentication_details_edges', 'symmetric_edge': False, 'inverse_edge_type': None},
    ])

    op.drop_column('user_authentications', 'user_id')
    op.drop_index('user_saved_authentication_details_edges_time_idx',
                  table_name='user_saved_authentication_details_edges')
    op.drop_table('user_saved_authentication_details_edges')
    # ### end Alembic commands ###
