# Code generated by github.com/lolopinto/ent/ent, DO NOT edit.

"""drop index user_authentication_users_edges_time_idx from user_authentication_users_edges
drop user_authentication_users_edges table

Revision ID: 677cf37aa4de
Revises: 10acebc9b531
Create Date: 2021-08-15 22:48:05.315822+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '677cf37aa4de'
down_revision = '10acebc9b531'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user_authentication_users_edges_time_idx',
                  table_name='user_authentication_users_edges')
    op.drop_table('user_authentication_users_edges')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_authentication_users_edges',
                    sa.Column('id1', postgresql.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('id1_type', sa.TEXT(),
                              autoincrement=False, nullable=False),
                    sa.Column('edge_type', postgresql.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('id2', postgresql.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('id2_type', sa.TEXT(),
                              autoincrement=False, nullable=False),
                    sa.Column('time', postgresql.TIMESTAMP(),
                              autoincrement=False, nullable=False),
                    sa.Column('data', sa.TEXT(),
                              autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint(
                        'id1', 'edge_type', 'id2', name='user_authentication_users_edges_id1_edge_type_id2_pkey')
                    )
    op.create_index('user_authentication_users_edges_time_idx',
                    'user_authentication_users_edges', ['time'], unique=False)
    # ### end Alembic commands ###
