# Code generated by github.com/lolopinto/ent/ent, DO NOT edit.

"""add user_authentication_users_edges table
add index user_authentication_users_edges_time_idx to user_authentication_users_edges
drop index user_authentication_user_auth_edges_time_idx from user_authentication_user_auth_edges
drop user_authentication_user_auth_edges table
add edge UserAuthenticationToUsersEdge

Revision ID: 8eac18cc7ada
Revises: eb065f808850
Create Date: 2021-08-15 22:29:02.495964+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8eac18cc7ada'
down_revision = 'eb065f808850'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_authentication_users_edges',
                    sa.Column('id1', postgresql.UUID(), nullable=False),
                    sa.Column('id1_type', sa.Text(), nullable=False),
                    sa.Column('edge_type', postgresql.UUID(), nullable=False),
                    sa.Column('id2', postgresql.UUID(), nullable=False),
                    sa.Column('id2_type', sa.Text(), nullable=False),
                    sa.Column('time', sa.TIMESTAMP(), nullable=False),
                    sa.Column('data', sa.Text(), nullable=True),
                    sa.PrimaryKeyConstraint(
                        'id1', 'edge_type', 'id2', name='user_authentication_users_edges_id1_edge_type_id2_pkey')
                    )
    op.create_index('user_authentication_users_edges_time_idx',
                    'user_authentication_users_edges', ['time'], unique=False)
    op.drop_index('user_authentication_user_auth_edges_time_idx',
                  table_name='user_authentication_user_auth_edges')
    op.drop_table('user_authentication_user_auth_edges')
    op.add_edges([
        {'edge_name': 'UserAuthenticationToUsersEdge', 'edge_type': 'c13e77f9-9577-4fc4-b280-77b9a963e24a',
            'edge_table': 'user_authentication_users_edges', 'symmetric_edge': False, 'inverse_edge_type': '4254e11b-8166-4d4e-b6a3-4dd76a669658'},
    ])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.remove_edges([
        {'edge_name': 'UserAuthenticationToUsersEdge', 'edge_type': 'c13e77f9-9577-4fc4-b280-77b9a963e24a',
            'edge_table': 'user_authentication_users_edges', 'symmetric_edge': False, 'inverse_edge_type': '4254e11b-8166-4d4e-b6a3-4dd76a669658'},
    ])

    op.create_table('user_authentication_user_auth_edges',
                    sa.Column('id1', postgresql.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('id1_type', sa.TEXT(),
                              autoincrement=False, nullable=False),
                    sa.Column('edge_type', postgresql.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('id2', postgresql.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('id2_type', sa.TEXT(),
                              autoincrement=False, nullable=False),
                    sa.Column('time', postgresql.TIMESTAMP(),
                              autoincrement=False, nullable=False),
                    sa.Column('data', sa.TEXT(),
                              autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint(
                        'id1', 'edge_type', 'id2', name='user_authentication_user_auth_edges_id1_edge_type_id2_pkey')
                    )
    op.create_index('user_authentication_user_auth_edges_time_idx',
                    'user_authentication_user_auth_edges', ['time'], unique=False)
    op.drop_index('user_authentication_users_edges_time_idx',
                  table_name='user_authentication_users_edges')
    op.drop_table('user_authentication_users_edges')
    # ### end Alembic commands ###
