# Code generated by github.com/lolopinto/ent/ent, DO NOT edit.

"""add user_authentications table

Revision ID: ab645d2bc5bf
Revises: f840b3210922
Create Date: 2021-08-15 21:29:32.907623+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ab645d2bc5bf'
down_revision = 'f840b3210922'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_authentications',
                    sa.Column('id', postgresql.UUID(), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
                    sa.Column('email_address', sa.Text(), nullable=False),
                    sa.Column('password', sa.Text(), nullable=False),
                    sa.PrimaryKeyConstraint(
                        'id', name='user_authentications_id_pkey'),
                    sa.UniqueConstraint(
                        'email_address', name='user_authentications_unique_email_address')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_authentications')
    # ### end Alembic commands ###
