# Code generated by github.com/lolopinto/ent/ent, DO NOT edit.

"""add answer_authors_edges table
add index answer_authors_edges_time_idx to answer_authors_edges
add answers table
add question_answers_edges table
add index question_answers_edges_time_idx to question_answers_edges
add user_authored_answers_edges table
add index user_authored_answers_edges_time_idx to user_authored_answers_edges
add edges AnswerToAuthorsEdge, QuestionToAnswersEdge, UserToAuthorToAuthoredAnswersEdge, UserToAuthoredAnswersEdge

Revision ID: afe9c525d818
Revises: c9d469b0159b
Create Date: 2021-06-23 08:44:52.344278+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'afe9c525d818'
down_revision = 'c9d469b0159b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer_authors_edges',
                    sa.Column('id1', postgresql.UUID(), nullable=False),
                    sa.Column('id1_type', sa.Text(), nullable=False),
                    sa.Column('edge_type', postgresql.UUID(), nullable=False),
                    sa.Column('id2', postgresql.UUID(), nullable=False),
                    sa.Column('id2_type', sa.Text(), nullable=False),
                    sa.Column('time', sa.TIMESTAMP(), nullable=False),
                    sa.Column('data', sa.Text(), nullable=True),
                    sa.PrimaryKeyConstraint(
                        'id1', 'edge_type', 'id2', name='answer_authors_edges_id1_edge_type_id2_pkey')
                    )
    op.create_index('answer_authors_edges_time_idx',
                    'answer_authors_edges', ['time'], unique=False)
    op.create_table('answers',
                    sa.Column('id', postgresql.UUID(), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
                    sa.Column('body', sa.Text(), nullable=False),
                    sa.Column('accepted_answer', sa.Boolean(), nullable=False),
                    sa.Column('question_id', postgresql.UUID(),
                              nullable=False),
                    sa.Column('user_id', postgresql.UUID(), nullable=False),
                    sa.PrimaryKeyConstraint('id', name='answers_id_pkey')
                    )
    op.create_table('question_answers_edges',
                    sa.Column('id1', postgresql.UUID(), nullable=False),
                    sa.Column('id1_type', sa.Text(), nullable=False),
                    sa.Column('edge_type', postgresql.UUID(), nullable=False),
                    sa.Column('id2', postgresql.UUID(), nullable=False),
                    sa.Column('id2_type', sa.Text(), nullable=False),
                    sa.Column('time', sa.TIMESTAMP(), nullable=False),
                    sa.Column('data', sa.Text(), nullable=True),
                    sa.PrimaryKeyConstraint(
                        'id1', 'edge_type', 'id2', name='question_answers_edges_id1_edge_type_id2_pkey')
                    )
    op.create_index('question_answers_edges_time_idx',
                    'question_answers_edges', ['time'], unique=False)
    op.create_table('user_authored_answers_edges',
                    sa.Column('id1', postgresql.UUID(), nullable=False),
                    sa.Column('id1_type', sa.Text(), nullable=False),
                    sa.Column('edge_type', postgresql.UUID(), nullable=False),
                    sa.Column('id2', postgresql.UUID(), nullable=False),
                    sa.Column('id2_type', sa.Text(), nullable=False),
                    sa.Column('time', sa.TIMESTAMP(), nullable=False),
                    sa.Column('data', sa.Text(), nullable=True),
                    sa.PrimaryKeyConstraint(
                        'id1', 'edge_type', 'id2', name='user_authored_answers_edges_id1_edge_type_id2_pkey')
                    )
    op.create_index('user_authored_answers_edges_time_idx',
                    'user_authored_answers_edges', ['time'], unique=False)
    op.add_edges([
        {'edge_name': 'AnswerToAuthorsEdge', 'edge_type': '6226f374-ada1-4acb-a1d3-f0f3e1603ba6',
            'edge_table': 'answer_authors_edges', 'symmetric_edge': False, 'inverse_edge_type': '334a0a65-f4bf-4119-b1b8-7e60e86c5374'},
        {'edge_name': 'QuestionToAnswersEdge', 'edge_type': '69eb1cb3-9fa7-437b-8474-21092a525de7',
            'edge_table': 'question_answers_edges', 'symmetric_edge': False, 'inverse_edge_type': None},
        {'edge_name': 'UserToAuthorToAuthoredAnswersEdge', 'edge_type': '334a0a65-f4bf-4119-b1b8-7e60e86c5374',
            'edge_table': 'answer_authors_edges', 'symmetric_edge': False, 'inverse_edge_type': '6226f374-ada1-4acb-a1d3-f0f3e1603ba6'},
        {'edge_name': 'UserToAuthoredAnswersEdge', 'edge_type': 'b39d9e6f-2249-4c6c-b4b3-e8c14430b60e',
            'edge_table': 'user_authored_answers_edges', 'symmetric_edge': False, 'inverse_edge_type': None},
    ])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.remove_edges([
        {'edge_name': 'AnswerToAuthorsEdge', 'edge_type': '6226f374-ada1-4acb-a1d3-f0f3e1603ba6',
            'edge_table': 'answer_authors_edges', 'symmetric_edge': False, 'inverse_edge_type': '334a0a65-f4bf-4119-b1b8-7e60e86c5374'},
        {'edge_name': 'QuestionToAnswersEdge', 'edge_type': '69eb1cb3-9fa7-437b-8474-21092a525de7',
            'edge_table': 'question_answers_edges', 'symmetric_edge': False, 'inverse_edge_type': None},
        {'edge_name': 'UserToAuthorToAuthoredAnswersEdge', 'edge_type': '334a0a65-f4bf-4119-b1b8-7e60e86c5374',
            'edge_table': 'answer_authors_edges', 'symmetric_edge': False, 'inverse_edge_type': '6226f374-ada1-4acb-a1d3-f0f3e1603ba6'},
        {'edge_name': 'UserToAuthoredAnswersEdge', 'edge_type': 'b39d9e6f-2249-4c6c-b4b3-e8c14430b60e',
            'edge_table': 'user_authored_answers_edges', 'symmetric_edge': False, 'inverse_edge_type': None},
    ])

    op.drop_index('user_authored_answers_edges_time_idx',
                  table_name='user_authored_answers_edges')
    op.drop_table('user_authored_answers_edges')
    op.drop_index('question_answers_edges_time_idx',
                  table_name='question_answers_edges')
    op.drop_table('question_answers_edges')
    op.drop_table('answers')
    op.drop_index('answer_authors_edges_time_idx',
                  table_name='answer_authors_edges')
    op.drop_table('answer_authors_edges')
    # ### end Alembic commands ###
