# Code generated by github.com/lolopinto/ent/ent, DO NOT edit.

"""drop index question_title from questions

Revision ID: b403ab255274
Revises: d9bd38f8eb6b
Create Date: 2021-08-10 12:59:55.299745+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'b403ab255274'
down_revision = 'd9bd38f8eb6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('question_title', table_name='questions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('question_title', 'questions', ['title'], unique=False)
    # ### end Alembic commands ###
