# Code generated by github.com/lolopinto/ent/ent, DO NOT edit.

"""add index email_address to user_authentications
add index owner to user_authentications

Revision ID: bd8c2db315e8
Revises: 5d35440812f8
Create Date: 2021-08-15 21:44:23.972281+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'bd8c2db315e8'
down_revision = '5d35440812f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('email_address', 'user_authentications',
                    ['email_address'], unique=False)
    op.create_index('owner', 'user_authentications', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('owner', table_name='user_authentications')
    op.drop_index('email_address', table_name='user_authentications')
    # ### end Alembic commands ###
