# Code generated by github.com/lolopinto/ent/ent, DO NOT edit.

"""add question_authors_edges table
add index question_authors_edges_time_idx to question_authors_edges
add edge UserToAuthorToAuthoredQuestionsEdge
modify edge QuestionToAuthorsEdge

Revision ID: c9d469b0159b
Revises: a11f1f55aff7
Create Date: 2021-06-21 21:12:16.979366+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c9d469b0159b'
down_revision = 'a11f1f55aff7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_authors_edges',
                    sa.Column('id1', postgresql.UUID(), nullable=False),
                    sa.Column('id1_type', sa.Text(), nullable=False),
                    sa.Column('edge_type', postgresql.UUID(), nullable=False),
                    sa.Column('id2', postgresql.UUID(), nullable=False),
                    sa.Column('id2_type', sa.Text(), nullable=False),
                    sa.Column('time', sa.TIMESTAMP(), nullable=False),
                    sa.Column('data', sa.Text(), nullable=True),
                    sa.PrimaryKeyConstraint(
                        'id1', 'edge_type', 'id2', name='question_authors_edges_id1_edge_type_id2_pkey')
                    )
    op.create_index('question_authors_edges_time_idx',
                    'question_authors_edges', ['time'], unique=False)
    op.add_edges([
        {'edge_name': 'UserToAuthorToAuthoredQuestionsEdge', 'edge_type': 'f5f98bc4-94ed-4b3d-88b5-628992440185',
            'edge_table': 'question_authors_edges', 'symmetric_edge': False, 'inverse_edge_type': 'dbdae75e-1072-438e-8713-4f4284b289ad'},
    ])

    op.modify_edge(
        'dbdae75e-1072-438e-8713-4f4284b289ad',
        {'edge_name': 'QuestionToAuthorsEdge', 'edge_type': 'dbdae75e-1072-438e-8713-4f4284b289ad',
            'edge_table': 'question_authors_edges', 'symmetric_edge': False, 'inverse_edge_type': 'f5f98bc4-94ed-4b3d-88b5-628992440185'},

    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.modify_edge(
        'dbdae75e-1072-438e-8713-4f4284b289ad',
        {'edge_type': UUID('dbdae75e-1072-438e-8713-4f4284b289ad'), 'edge_name': 'QuestionToAuthorsEdge', 'symmetric_edge': False,
         'inverse_edge_type': UUID('eb398e63-df78-40d2-9e86-50a3a788c88f'), 'edge_table': 'question_authors_edges'},

    )
    op.remove_edges([
        {'edge_name': 'UserToAuthorToAuthoredQuestionsEdge', 'edge_type': 'f5f98bc4-94ed-4b3d-88b5-628992440185',
            'edge_table': 'question_authors_edges', 'symmetric_edge': False, 'inverse_edge_type': 'dbdae75e-1072-438e-8713-4f4284b289ad'},
    ])

    op.drop_index('question_authors_edges_time_idx',
                  table_name='question_authors_edges')
    op.drop_table('question_authors_edges')
    # ### end Alembic commands ###
