# Code generated by github.com/lolopinto/ent/ent, DO NOT edit.

"""drop index user_saved_authentication_details_edges_time_idx from user_saved_authentication_details_edges
drop user_saved_authentication_details_edges table

Revision ID: d4b42cf48710
Revises: 677cf37aa4de
Create Date: 2021-08-15 23:00:40.772942+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd4b42cf48710'
down_revision = '677cf37aa4de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user_saved_authentication_details_edges_time_idx',
                  table_name='user_saved_authentication_details_edges')
    op.drop_table('user_saved_authentication_details_edges')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_saved_authentication_details_edges',
                    sa.Column('id1', postgresql.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('id1_type', sa.TEXT(),
                              autoincrement=False, nullable=False),
                    sa.Column('edge_type', postgresql.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('id2', postgresql.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('id2_type', sa.TEXT(),
                              autoincrement=False, nullable=False),
                    sa.Column('time', postgresql.TIMESTAMP(),
                              autoincrement=False, nullable=False),
                    sa.Column('data', sa.TEXT(),
                              autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint(
                        'id1', 'edge_type', 'id2', name='user_saved_authentication_details_edges_id1_edge_type_id2_pkey')
                    )
    op.create_index('user_saved_authentication_details_edges_time_idx',
                    'user_saved_authentication_details_edges', ['time'], unique=False)
    # ### end Alembic commands ###
