# Code generated by github.com/lolopinto/ent/ent, DO NOT edit.

"""add user_auth_details_edges table
add index user_auth_details_edges_time_idx to user_auth_details_edges
add user_authentication_user_auth_edges table
add index user_authentication_user_auth_edges_time_idx to user_authentication_user_auth_edges
drop index user_saved_authentication_details_edges_time_idx from user_saved_authentication_details_edges
drop user_saved_authentication_details_edges table
add edges UserAuthenticationToUserAuthEdge, UserToAuthDetailsEdge

Revision ID: eb065f808850
Revises: bd8c2db315e8
Create Date: 2021-08-15 22:17:46.776802+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eb065f808850'
down_revision = 'bd8c2db315e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_auth_details_edges',
                    sa.Column('id1', postgresql.UUID(), nullable=False),
                    sa.Column('id1_type', sa.Text(), nullable=False),
                    sa.Column('edge_type', postgresql.UUID(), nullable=False),
                    sa.Column('id2', postgresql.UUID(), nullable=False),
                    sa.Column('id2_type', sa.Text(), nullable=False),
                    sa.Column('time', sa.TIMESTAMP(), nullable=False),
                    sa.Column('data', sa.Text(), nullable=True),
                    sa.PrimaryKeyConstraint(
                        'id1', 'edge_type', 'id2', name='user_auth_details_edges_id1_edge_type_id2_pkey')
                    )
    op.create_index('user_auth_details_edges_time_idx',
                    'user_auth_details_edges', ['time'], unique=False)
    op.create_table('user_authentication_user_auth_edges',
                    sa.Column('id1', postgresql.UUID(), nullable=False),
                    sa.Column('id1_type', sa.Text(), nullable=False),
                    sa.Column('edge_type', postgresql.UUID(), nullable=False),
                    sa.Column('id2', postgresql.UUID(), nullable=False),
                    sa.Column('id2_type', sa.Text(), nullable=False),
                    sa.Column('time', sa.TIMESTAMP(), nullable=False),
                    sa.Column('data', sa.Text(), nullable=True),
                    sa.PrimaryKeyConstraint(
                        'id1', 'edge_type', 'id2', name='user_authentication_user_auth_edges_id1_edge_type_id2_pkey')
                    )
    op.create_index('user_authentication_user_auth_edges_time_idx',
                    'user_authentication_user_auth_edges', ['time'], unique=False)
    op.drop_index('user_saved_authentication_details_edges_time_idx',
                  table_name='user_saved_authentication_details_edges')
    op.drop_table('user_saved_authentication_details_edges')
    op.add_edges([
        {'edge_name': 'UserAuthenticationToUserAuthEdge', 'edge_type': '8ee90b44-8c12-4a42-b758-82b9addd505b',
            'edge_table': 'user_authentication_user_auth_edges', 'symmetric_edge': False, 'inverse_edge_type': '4254e11b-8166-4d4e-b6a3-4dd76a669658'},
        {'edge_name': 'UserToAuthDetailsEdge', 'edge_type': '4254e11b-8166-4d4e-b6a3-4dd76a669658',
            'edge_table': 'user_auth_details_edges', 'symmetric_edge': False, 'inverse_edge_type': None},
    ])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.remove_edges([
        {'edge_name': 'UserAuthenticationToUserAuthEdge', 'edge_type': '8ee90b44-8c12-4a42-b758-82b9addd505b',
            'edge_table': 'user_authentication_user_auth_edges', 'symmetric_edge': False, 'inverse_edge_type': '4254e11b-8166-4d4e-b6a3-4dd76a669658'},
        {'edge_name': 'UserToAuthDetailsEdge', 'edge_type': '4254e11b-8166-4d4e-b6a3-4dd76a669658',
            'edge_table': 'user_auth_details_edges', 'symmetric_edge': False, 'inverse_edge_type': None},
    ])

    op.create_table('user_saved_authentication_details_edges',
                    sa.Column('id1', postgresql.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('id1_type', sa.TEXT(),
                              autoincrement=False, nullable=False),
                    sa.Column('edge_type', postgresql.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('id2', postgresql.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('id2_type', sa.TEXT(),
                              autoincrement=False, nullable=False),
                    sa.Column('time', postgresql.TIMESTAMP(),
                              autoincrement=False, nullable=False),
                    sa.Column('data', sa.TEXT(),
                              autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint(
                        'id1', 'edge_type', 'id2', name='user_saved_authentication_details_edges_id1_edge_type_id2_pkey')
                    )
    op.create_index('user_saved_authentication_details_edges_time_idx',
                    'user_saved_authentication_details_edges', ['time'], unique=False)
    op.drop_index('user_authentication_user_auth_edges_time_idx',
                  table_name='user_authentication_user_auth_edges')
    op.drop_table('user_authentication_user_auth_edges')
    op.drop_index('user_auth_details_edges_time_idx',
                  table_name='user_auth_details_edges')
    op.drop_table('user_auth_details_edges')
    # ### end Alembic commands ###
