# Code generated by github.com/lolopinto/ent/ent, DO NOT edit.

"""add enum answer_vote_type
add answer_vote_voters_edges table
add index answer_vote_voters_edges_time_idx to answer_vote_voters_edges
add answer_votes table
add answer_votes_edges table
add index answer_votes_edges_time_idx to answer_votes_edges
add user_answers_voted_edges table
add index user_answers_voted_edges_time_idx to user_answers_voted_edges
add edges AnswerToVotesEdge, AnswerVoteToVotersEdge, UserToAnswersVotedEdge, UserToVoterToAnswersVotedEdge

Revision ID: f840b3210922
Revises: 0ff0721605a7
Create Date: 2021-08-12 22:12:16.213527+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f840b3210922'
down_revision = '0ff0721605a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_enum_type('answer_vote_type', ['up', 'down'])
    op.create_table('answer_vote_voters_edges',
                    sa.Column('id1', postgresql.UUID(), nullable=False),
                    sa.Column('id1_type', sa.Text(), nullable=False),
                    sa.Column('edge_type', postgresql.UUID(), nullable=False),
                    sa.Column('id2', postgresql.UUID(), nullable=False),
                    sa.Column('id2_type', sa.Text(), nullable=False),
                    sa.Column('time', sa.TIMESTAMP(), nullable=False),
                    sa.Column('data', sa.Text(), nullable=True),
                    sa.PrimaryKeyConstraint(
                        'id1', 'edge_type', 'id2', name='answer_vote_voters_edges_id1_edge_type_id2_pkey')
                    )
    op.create_index('answer_vote_voters_edges_time_idx',
                    'answer_vote_voters_edges', ['time'], unique=False)
    op.create_table('answer_votes',
                    sa.Column('id', postgresql.UUID(), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
                    sa.Column('answer_vote_type', postgresql.ENUM('up', 'down',
                                                                  name='answer_vote_type', create_type=False), nullable=False),
                    sa.Column('answer_id', postgresql.UUID(), nullable=False),
                    sa.Column('user_id', postgresql.UUID(), nullable=False),
                    sa.PrimaryKeyConstraint('id', name='answer_votes_id_pkey'),
                    sa.UniqueConstraint('user_id', 'answer_id',
                                        name='uniqueAnswerVoteVoter')
                    )
    op.create_table('answer_votes_edges',
                    sa.Column('id1', postgresql.UUID(), nullable=False),
                    sa.Column('id1_type', sa.Text(), nullable=False),
                    sa.Column('edge_type', postgresql.UUID(), nullable=False),
                    sa.Column('id2', postgresql.UUID(), nullable=False),
                    sa.Column('id2_type', sa.Text(), nullable=False),
                    sa.Column('time', sa.TIMESTAMP(), nullable=False),
                    sa.Column('data', sa.Text(), nullable=True),
                    sa.PrimaryKeyConstraint('id1', 'edge_type', 'id2',
                                            name='answer_votes_edges_id1_edge_type_id2_pkey')
                    )
    op.create_index('answer_votes_edges_time_idx',
                    'answer_votes_edges', ['time'], unique=False)
    op.create_table('user_answers_voted_edges',
                    sa.Column('id1', postgresql.UUID(), nullable=False),
                    sa.Column('id1_type', sa.Text(), nullable=False),
                    sa.Column('edge_type', postgresql.UUID(), nullable=False),
                    sa.Column('id2', postgresql.UUID(), nullable=False),
                    sa.Column('id2_type', sa.Text(), nullable=False),
                    sa.Column('time', sa.TIMESTAMP(), nullable=False),
                    sa.Column('data', sa.Text(), nullable=True),
                    sa.PrimaryKeyConstraint(
                        'id1', 'edge_type', 'id2', name='user_answers_voted_edges_id1_edge_type_id2_pkey')
                    )
    op.create_index('user_answers_voted_edges_time_idx',
                    'user_answers_voted_edges', ['time'], unique=False)
    op.add_edges([
        {'edge_name': 'AnswerToVotesEdge', 'edge_type': 'c60240be-8b1e-4987-a87e-0934a6d3f29a',
            'edge_table': 'answer_votes_edges', 'symmetric_edge': False, 'inverse_edge_type': None},
        {'edge_name': 'AnswerVoteToVotersEdge', 'edge_type': '1b97dcf2-04fc-4a1c-9625-9cbd090be224',
            'edge_table': 'answer_vote_voters_edges', 'symmetric_edge': False, 'inverse_edge_type': 'e11767f0-385f-40d0-83de-4100463fd65a'},
        {'edge_name': 'UserToAnswersVotedEdge', 'edge_type': '7293e3fd-0ddd-424c-a740-27392e885d7e',
            'edge_table': 'user_answers_voted_edges', 'symmetric_edge': False, 'inverse_edge_type': None},
        {'edge_name': 'UserToVoterToAnswersVotedEdge', 'edge_type': 'e11767f0-385f-40d0-83de-4100463fd65a',
            'edge_table': 'answer_vote_voters_edges', 'symmetric_edge': False, 'inverse_edge_type': '1b97dcf2-04fc-4a1c-9625-9cbd090be224'},
    ])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.remove_edges([
        {'edge_name': 'AnswerToVotesEdge', 'edge_type': 'c60240be-8b1e-4987-a87e-0934a6d3f29a',
            'edge_table': 'answer_votes_edges', 'symmetric_edge': False, 'inverse_edge_type': None},
        {'edge_name': 'AnswerVoteToVotersEdge', 'edge_type': '1b97dcf2-04fc-4a1c-9625-9cbd090be224',
            'edge_table': 'answer_vote_voters_edges', 'symmetric_edge': False, 'inverse_edge_type': 'e11767f0-385f-40d0-83de-4100463fd65a'},
        {'edge_name': 'UserToAnswersVotedEdge', 'edge_type': '7293e3fd-0ddd-424c-a740-27392e885d7e',
            'edge_table': 'user_answers_voted_edges', 'symmetric_edge': False, 'inverse_edge_type': None},
        {'edge_name': 'UserToVoterToAnswersVotedEdge', 'edge_type': 'e11767f0-385f-40d0-83de-4100463fd65a',
            'edge_table': 'answer_vote_voters_edges', 'symmetric_edge': False, 'inverse_edge_type': '1b97dcf2-04fc-4a1c-9625-9cbd090be224'},
    ])

    op.drop_index('user_answers_voted_edges_time_idx',
                  table_name='user_answers_voted_edges')
    op.drop_table('user_answers_voted_edges')
    op.drop_index('answer_votes_edges_time_idx',
                  table_name='answer_votes_edges')
    op.drop_table('answer_votes_edges')
    op.drop_table('answer_votes')
    op.drop_index('answer_vote_voters_edges_time_idx',
                  table_name='answer_vote_voters_edges')
    op.drop_table('answer_vote_voters_edges')
    op.drop_enum_type('answer_vote_type', ['up', 'down'])
    # ### end Alembic commands ###
