// Generated by github.com/lolopinto/ent/ent, DO NOT EDIT.

import { AssocEdgeInputOptions, Ent, ID, Viewer } from "@snowtop/ent";
import {
  Action,
  Builder,
  Changeset,
  Orchestrator,
  WriteOperation,
  saveBuilder,
  saveBuilderX,
} from "@snowtop/ent/action";
import { Answer, AnswerVote, AnswerVoteType, User } from "src/ent/";
import { EdgeType, NodeType } from "src/ent/const";
import schema from "src/schema/answer_vote";

export interface AnswerVoteInput {
  answerVoteType?: AnswerVoteType;
  answerID?: ID | Builder<Answer>;
  voterID?: ID | Builder<User>;
}

export interface AnswerVoteAction extends Action<AnswerVote> {
  getInput(): AnswerVoteInput;
}

function randomNum(): string {
  return Math.random().toString(10).substring(2);
}

export class AnswerVoteBuilder implements Builder<AnswerVote> {
  orchestrator: Orchestrator<AnswerVote>;
  readonly placeholderID: ID;
  readonly ent = AnswerVote;
  private input: AnswerVoteInput;

  public constructor(
    public readonly viewer: Viewer,
    public readonly operation: WriteOperation,
    action: AnswerVoteAction,
    public readonly existingEnt?: AnswerVote | undefined,
  ) {
    this.placeholderID = `$ent.idPlaceholderID$ ${randomNum()}-AnswerVote`;
    this.input = action.getInput();

    this.orchestrator = new Orchestrator({
      viewer: viewer,
      operation: this.operation,
      tableName: "answer_votes",
      key: "id",
      loaderOptions: AnswerVote.loaderOptions(),
      builder: this,
      action: action,
      schema: schema,
      editedFields: () => {
        return this.getEditedFields.apply(this);
      },
    });
  }

  getInput(): AnswerVoteInput {
    return this.input;
  }

  updateInput(input: AnswerVoteInput) {
    // override input
    this.input = {
      ...this.input,
      ...input,
    };
  }

  // this gets the inputs that have been written for a given edgeType and operation
  // WriteOperation.Insert for adding an edge and WriteOperation.Delete for deleting an edge
  getEdgeInputData(edgeType: EdgeType, op: WriteOperation) {
    return this.orchestrator.getInputEdges(edgeType, op);
  }

  clearInputEdges(edgeType: EdgeType, op: WriteOperation, id?: ID) {
    this.orchestrator.clearInputEdges(edgeType, op, id);
  }
  addVoter(...ids: ID[]): AnswerVoteBuilder;
  addVoter(...nodes: User[]): AnswerVoteBuilder;
  addVoter(...nodes: Builder<User>[]): AnswerVoteBuilder;
  addVoter(...nodes: ID[] | User[] | Builder<User>[]): AnswerVoteBuilder {
    for (const node of nodes) {
      if (this.isBuilder(node)) {
        this.addVoterID(node);
      } else if (typeof node === "object") {
        this.addVoterID(node.id);
      } else {
        this.addVoterID(node);
      }
    }
    return this;
  }

  addVoterID(
    id: ID | Builder<User>,
    options?: AssocEdgeInputOptions,
  ): AnswerVoteBuilder {
    this.orchestrator.addOutboundEdge(
      id,
      EdgeType.AnswerVoteToVoters,
      NodeType.User,
      options,
    );
    return this;
  }

  removeVoter(...ids: ID[]): AnswerVoteBuilder;
  removeVoter(...nodes: User[]): AnswerVoteBuilder;
  removeVoter(...nodes: ID[] | User[]): AnswerVoteBuilder {
    for (const node of nodes) {
      if (typeof node === "object") {
        this.orchestrator.removeOutboundEdge(
          node.id,
          EdgeType.AnswerVoteToVoters,
        );
      } else {
        this.orchestrator.removeOutboundEdge(node, EdgeType.AnswerVoteToVoters);
      }
    }
    return this;
  }

  async build(): Promise<Changeset<AnswerVote>> {
    return this.orchestrator.build();
  }

  async valid(): Promise<boolean> {
    return this.orchestrator.valid();
  }

  async validX(): Promise<void> {
    return this.orchestrator.validX();
  }

  async save(): Promise<void> {
    await saveBuilder(this);
  }

  async saveX(): Promise<void> {
    await saveBuilderX(this);
  }

  async editedEnt(): Promise<AnswerVote | null> {
    return await this.orchestrator.editedEnt();
  }

  async editedEntX(): Promise<AnswerVote> {
    return await this.orchestrator.editedEntX();
  }

  private getEditedFields(): Map<string, any> {
    const fields = this.input;

    let result = new Map<string, any>();

    const addField = function (key: string, value: any) {
      if (value !== undefined) {
        result.set(key, value);
      }
    };
    addField("AnswerVoteType", fields.answerVoteType);
    addField("answerID", fields.answerID);
    if (fields.answerID) {
      this.orchestrator.addInboundEdge(
        fields.answerID,
        EdgeType.AnswerToVotes,
        NodeType.Answer,
      );
    }
    addField("voterID", fields.voterID);
    if (fields.voterID) {
      this.orchestrator.addInboundEdge(
        fields.voterID,
        EdgeType.UserToAnswersVoted,
        NodeType.User,
      );
    }
    return result;
  }

  isBuilder(node: ID | Ent | Builder<Ent>): node is Builder<Ent> {
    return (node as Builder<Ent>).placeholderID !== undefined;
  }

  // get value of AnswerVoteType. Retrieves it from the input if specified or takes it from existingEnt
  getNewAnswerVoteTypeValue(): AnswerVoteType | undefined {
    return this.input.answerVoteType || this.existingEnt?.answerVoteType;
  }

  // get value of answerID. Retrieves it from the input if specified or takes it from existingEnt
  getNewAnswerIDValue(): ID | Builder<Answer> | undefined {
    return this.input.answerID || this.existingEnt?.answerID;
  }

  // get value of voterID. Retrieves it from the input if specified or takes it from existingEnt
  getNewVoterIDValue(): ID | Builder<User> | undefined {
    return this.input.voterID || this.existingEnt?.voterID;
  }
}
