// Generated by github.com/lolopinto/ent/ent, DO NOT EDIT.

import { AssocEdgeInputOptions, Ent, ID, Viewer } from "@lolopinto/ent";
import {
  Action,
  Builder,
  Changeset,
  Orchestrator,
  WriteOperation,
  saveBuilder,
  saveBuilderX,
} from "@lolopinto/ent/action";
import { Question, User } from "src/ent/";
import { EdgeType, NodeType } from "src/ent/const";
import schema from "src/schema/user";

export interface UserInput {
  firstName?: string;
  lastName?: string;
  emailAddress?: string;
  password?: string;
}

export interface UserAction extends Action<User> {
  getInput(): UserInput;
}

function randomNum(): string {
  return Math.random().toString(10).substring(2);
}

export class UserBuilder implements Builder<User> {
  orchestrator: Orchestrator<User>;
  readonly placeholderID: ID;
  readonly ent = User;
  private input: UserInput;

  public constructor(
    public readonly viewer: Viewer,
    public readonly operation: WriteOperation,
    action: UserAction,
    public readonly existingEnt?: User | undefined,
  ) {
    this.placeholderID = `$ent.idPlaceholderID$ ${randomNum()}-User`;
    this.input = action.getInput();

    this.orchestrator = new Orchestrator({
      viewer: viewer,
      operation: this.operation,
      tableName: "users",
      key: "id",
      loaderOptions: User.loaderOptions(),
      builder: this,
      action: action,
      schema: schema,
      editedFields: () => {
        return this.getEditedFields.apply(this);
      },
    });
  }

  getInput(): UserInput {
    return this.input;
  }

  updateInput(input: UserInput) {
    // override input
    this.input = {
      ...this.input,
      ...input,
    };
  }

  // this gets the inputs that have been written for a given edgeType and operation
  // WriteOperation.Insert for adding an edge and WriteOperation.Delete for deleting an edge
  getEdgeInputData(edgeType: EdgeType, op: WriteOperation) {
    return this.orchestrator.getInputEdges(edgeType, op);
  }

  clearInputEdges(edgeType: EdgeType, op: WriteOperation, id?: ID) {
    this.orchestrator.clearInputEdges(edgeType, op, id);
  }
  addAuthorToAuthoredQuestion(...ids: ID[]): UserBuilder;
  addAuthorToAuthoredQuestion(...nodes: Question[]): UserBuilder;
  addAuthorToAuthoredQuestion(...nodes: Builder<Question>[]): UserBuilder;
  addAuthorToAuthoredQuestion(
    ...nodes: ID[] | Question[] | Builder<Question>[]
  ): UserBuilder {
    for (const node of nodes) {
      if (this.isBuilder(node)) {
        this.addAuthorToAuthoredQuestionID(node);
      } else if (typeof node === "object") {
        this.addAuthorToAuthoredQuestionID(node.id);
      } else {
        this.addAuthorToAuthoredQuestionID(node);
      }
    }
    return this;
  }

  addAuthorToAuthoredQuestionID(
    id: ID | Builder<Question>,
    options?: AssocEdgeInputOptions,
  ): UserBuilder {
    this.orchestrator.addOutboundEdge(
      id,
      EdgeType.UserToAuthorToAuthoredQuestions,
      NodeType.Question,
      options,
    );
    return this;
  }

  removeAuthorToAuthoredQuestion(...ids: ID[]): UserBuilder;
  removeAuthorToAuthoredQuestion(...nodes: Question[]): UserBuilder;
  removeAuthorToAuthoredQuestion(...nodes: ID[] | Question[]): UserBuilder {
    for (const node of nodes) {
      if (typeof node === "object") {
        this.orchestrator.removeOutboundEdge(
          node.id,
          EdgeType.UserToAuthorToAuthoredQuestions,
        );
      } else {
        this.orchestrator.removeOutboundEdge(
          node,
          EdgeType.UserToAuthorToAuthoredQuestions,
        );
      }
    }
    return this;
  }

  addAuthoredQuestion(...ids: ID[]): UserBuilder;
  addAuthoredQuestion(...nodes: Question[]): UserBuilder;
  addAuthoredQuestion(...nodes: Builder<Question>[]): UserBuilder;
  addAuthoredQuestion(
    ...nodes: ID[] | Question[] | Builder<Question>[]
  ): UserBuilder {
    for (const node of nodes) {
      if (this.isBuilder(node)) {
        this.addAuthoredQuestionID(node);
      } else if (typeof node === "object") {
        this.addAuthoredQuestionID(node.id);
      } else {
        this.addAuthoredQuestionID(node);
      }
    }
    return this;
  }

  addAuthoredQuestionID(
    id: ID | Builder<Question>,
    options?: AssocEdgeInputOptions,
  ): UserBuilder {
    this.orchestrator.addOutboundEdge(
      id,
      EdgeType.UserToAuthoredQuestions,
      NodeType.Question,
      options,
    );
    return this;
  }

  removeAuthoredQuestion(...ids: ID[]): UserBuilder;
  removeAuthoredQuestion(...nodes: Question[]): UserBuilder;
  removeAuthoredQuestion(...nodes: ID[] | Question[]): UserBuilder {
    for (const node of nodes) {
      if (typeof node === "object") {
        this.orchestrator.removeOutboundEdge(
          node.id,
          EdgeType.UserToAuthoredQuestions,
        );
      } else {
        this.orchestrator.removeOutboundEdge(
          node,
          EdgeType.UserToAuthoredQuestions,
        );
      }
    }
    return this;
  }

  async build(): Promise<Changeset<User>> {
    return this.orchestrator.build();
  }

  async valid(): Promise<boolean> {
    return this.orchestrator.valid();
  }

  async validX(): Promise<void> {
    return this.orchestrator.validX();
  }

  async save(): Promise<void> {
    await saveBuilder(this);
  }

  async saveX(): Promise<void> {
    await saveBuilderX(this);
  }

  async editedEnt(): Promise<User | null> {
    return await this.orchestrator.editedEnt();
  }

  async editedEntX(): Promise<User> {
    return await this.orchestrator.editedEntX();
  }

  private getEditedFields(): Map<string, any> {
    const fields = this.input;

    let result = new Map<string, any>();

    const addField = function (key: string, value: any) {
      if (value !== undefined) {
        result.set(key, value);
      }
    };
    addField("FirstName", fields.firstName);
    addField("LastName", fields.lastName);
    addField("EmailAddress", fields.emailAddress);
    addField("Password", fields.password);
    return result;
  }

  isBuilder(node: ID | Ent | Builder<Ent>): node is Builder<Ent> {
    return (node as Builder<Ent>).placeholderID !== undefined;
  }

  // get value of FirstName. Retrieves it from the input if specified or takes it from existingEnt
  getNewFirstNameValue(): string | undefined {
    return this.input.firstName || this.existingEnt?.firstName;
  }

  // get value of LastName. Retrieves it from the input if specified or takes it from existingEnt
  getNewLastNameValue(): string | undefined {
    return this.input.lastName || this.existingEnt?.lastName;
  }

  // get value of EmailAddress. Retrieves it from the input if specified or takes it from existingEnt
  getNewEmailAddressValue(): string | undefined {
    return this.input.emailAddress || this.existingEnt?.emailAddress;
  }

  // get value of Password. Retrieves it from the input if specified or takes it from existingEnt
  getNewPasswordValue(): string | undefined {
    return this.input.password;
  }
}
