// Generated by github.com/lolopinto/ent/ent, DO NOT EDIT.

export enum NodeType {
  // Question is the node type for the Question object. Used to identify this node in edges and other places.
  Question = "question",
  // User is the node type for the User object. Used to identify this node in edges and other places.
  User = "user",
}

export function getNodeTypeValues() {
  return [NodeType.Question, NodeType.User];
}

export enum EdgeType {
  // QuestionToAuthors is the edgeType for the question to authors edge.
  QuestionToAuthors = "dbdae75e-1072-438e-8713-4f4284b289ad",
  // UserToAuthorToAuthoredQuestions is the edgeType for the user to authortoauthoredquestions edge.
  UserToAuthorToAuthoredQuestions = "f5f98bc4-94ed-4b3d-88b5-628992440185",
  // UserToAuthoredQuestions is the edgeType for the user to authoredquestions edge.
  UserToAuthoredQuestions = "eb398e63-df78-40d2-9e86-50a3a788c88f",
}

export function getEdgeTypeValues() {
  return [
    EdgeType.QuestionToAuthors,
    EdgeType.UserToAuthorToAuthoredQuestions,
    EdgeType.UserToAuthoredQuestions,
  ];
}
