// Generated by github.com/lolopinto/ent/ent, DO NOT EDIT.

export enum NodeType {
  // Answer is the node type for the Answer object. Used to identify this node in edges and other places.
  Answer = "answer",
  // AnswerComment is the node type for the AnswerComment object. Used to identify this node in edges and other places.
  AnswerComment = "answerComment",
  // Question is the node type for the Question object. Used to identify this node in edges and other places.
  Question = "question",
  // QuestionComment is the node type for the QuestionComment object. Used to identify this node in edges and other places.
  QuestionComment = "questionComment",
  // QuestionPrivateNote is the node type for the QuestionPrivateNote object. Used to identify this node in edges and other places.
  QuestionPrivateNote = "questionPrivateNote",
  // User is the node type for the User object. Used to identify this node in edges and other places.
  User = "user",
}

export function getNodeTypeValues() {
  return [
    NodeType.Answer,
    NodeType.AnswerComment,
    NodeType.Question,
    NodeType.QuestionComment,
    NodeType.QuestionPrivateNote,
    NodeType.User,
  ];
}

export enum EdgeType {
  // AnswerCommentToAuthors is the edgeType for the answerComment to authors edge.
  AnswerCommentToAuthors = "27e1aa22-2690-4253-81d4-d1e0cc263b50",
  // AnswerToAuthors is the edgeType for the answer to authors edge.
  AnswerToAuthors = "50274145-6c64-4693-a0c3-b19e38195a8f",
  // AnswerToComments is the edgeType for the answer to comments edge.
  AnswerToComments = "588823a4-f9bb-4c8a-bb76-8b9151ce2acc",
  // QuestionCommentToAuthors is the edgeType for the questionComment to authors edge.
  QuestionCommentToAuthors = "da0fd4ae-68e0-4fc7-a59d-8c4f70fa478e",
  // QuestionPrivateNoteToAuthors is the edgeType for the questionPrivateNote to authors edge.
  QuestionPrivateNoteToAuthors = "d17eba1c-8ce7-4262-83b5-0a0f880f6849",
  // QuestionToAnswers is the edgeType for the question to answers edge.
  QuestionToAnswers = "f5f7ab79-9f39-4f5e-878b-c0183f3e8617",
  // QuestionToAuthors is the edgeType for the question to authors edge.
  QuestionToAuthors = "f3795d44-be58-4b04-b434-4bb0d418f66b",
  // QuestionToComments is the edgeType for the question to comments edge.
  QuestionToComments = "c448499e-c78d-4e87-8627-b4c7f586a2f6",
  // QuestionToPrivateNotes is the edgeType for the question to privatenotes edge.
  QuestionToPrivateNotes = "da17ffb4-d545-403d-bb50-0f8a63c71792",
  // UserToAuthorToAuthoredAnswerComments is the edgeType for the user to authortoauthoredanswercomments edge.
  UserToAuthorToAuthoredAnswerComments = "b01a492e-281c-4844-9ef6-9dcfad9d4994",
  // UserToAuthorToAuthoredAnswers is the edgeType for the user to authortoauthoredanswers edge.
  UserToAuthorToAuthoredAnswers = "63a655cd-717a-4875-b0cb-3d515000de24",
  // UserToAuthorToAuthoredQuestionComments is the edgeType for the user to authortoauthoredquestioncomments edge.
  UserToAuthorToAuthoredQuestionComments = "c245f9ce-1461-4921-837a-40bc6ae9f726",
  // UserToAuthorToAuthoredQuestions is the edgeType for the user to authortoauthoredquestions edge.
  UserToAuthorToAuthoredQuestions = "afbc66d2-d1a1-4b2d-bf4f-0d5f81927995",
  // UserToAuthoredAnswerComments is the edgeType for the user to authoredanswercomments edge.
  UserToAuthoredAnswerComments = "cff7203e-9188-4ff2-a668-2ce33abd0a58",
  // UserToAuthoredAnswers is the edgeType for the user to authoredanswers edge.
  UserToAuthoredAnswers = "2e49fa7d-2b51-45d2-9e0f-7461c2c03039",
  // UserToAuthoredQuestionComments is the edgeType for the user to authoredquestioncomments edge.
  UserToAuthoredQuestionComments = "1d177e91-2f4f-4e98-9880-5e6778f16495",
  // UserToAuthoredQuestions is the edgeType for the user to authoredquestions edge.
  UserToAuthoredQuestions = "c9dae4e1-5325-4d9d-94e9-4a5417454eed",
  // UserToQuestionPrivateNotes is the edgeType for the user to questionprivatenotes edge.
  UserToQuestionPrivateNotes = "b6f4fe67-f4bf-47b6-a0b1-5153a56f2fb4",
  // UserToUserQuestionPrivateNotes is the edgeType for the user to userquestionprivatenotes edge.
  UserToUserQuestionPrivateNotes = "2fc54251-edbd-47ad-bdac-1af9306e3a8e",
}

export function getEdgeTypeValues() {
  return [
    EdgeType.AnswerCommentToAuthors,
    EdgeType.AnswerToAuthors,
    EdgeType.AnswerToComments,
    EdgeType.QuestionCommentToAuthors,
    EdgeType.QuestionPrivateNoteToAuthors,
    EdgeType.QuestionToAnswers,
    EdgeType.QuestionToAuthors,
    EdgeType.QuestionToComments,
    EdgeType.QuestionToPrivateNotes,
    EdgeType.UserToAuthorToAuthoredAnswerComments,
    EdgeType.UserToAuthorToAuthoredAnswers,
    EdgeType.UserToAuthorToAuthoredQuestionComments,
    EdgeType.UserToAuthorToAuthoredQuestions,
    EdgeType.UserToAuthoredAnswerComments,
    EdgeType.UserToAuthoredAnswers,
    EdgeType.UserToAuthoredQuestionComments,
    EdgeType.UserToAuthoredQuestions,
    EdgeType.UserToQuestionPrivateNotes,
    EdgeType.UserToUserQuestionPrivateNotes,
  ];
}
