// Generated by github.com/lolopinto/ent/ent, DO NOT EDIT.

export enum NodeType {
  // Answer is the node type for the Answer object. Used to identify this node in edges and other places.
  Answer = "answer",
  // AnswerComment is the node type for the AnswerComment object. Used to identify this node in edges and other places.
  AnswerComment = "answerComment",
  // AnswerVote is the node type for the AnswerVote object. Used to identify this node in edges and other places.
  AnswerVote = "answerVote",
  // Question is the node type for the Question object. Used to identify this node in edges and other places.
  Question = "question",
  // QuestionComment is the node type for the QuestionComment object. Used to identify this node in edges and other places.
  QuestionComment = "questionComment",
  // QuestionPrivateNote is the node type for the QuestionPrivateNote object. Used to identify this node in edges and other places.
  QuestionPrivateNote = "questionPrivateNote",
  // QuestionVote is the node type for the QuestionVote object. Used to identify this node in edges and other places.
  QuestionVote = "questionVote",
  // User is the node type for the User object. Used to identify this node in edges and other places.
  User = "user",
  // UserAuthentication is the node type for the UserAuthentication object. Used to identify this node in edges and other places.
  UserAuthentication = "userAuthentication",
}

export function getNodeTypeValues() {
  return [
    NodeType.Answer,
    NodeType.AnswerComment,
    NodeType.AnswerVote,
    NodeType.Question,
    NodeType.QuestionComment,
    NodeType.QuestionPrivateNote,
    NodeType.QuestionVote,
    NodeType.User,
    NodeType.UserAuthentication,
  ];
}

export enum EdgeType {
  // AnswerCommentToAuthors is the edgeType for the answerComment to authors edge.
  AnswerCommentToAuthors = "fdba641e-4f7e-4c7a-a1d1-fca2a1ed68dc",
  // AnswerToAuthors is the edgeType for the answer to authors edge.
  AnswerToAuthors = "6226f374-ada1-4acb-a1d3-f0f3e1603ba6",
  // AnswerToComments is the edgeType for the answer to comments edge.
  AnswerToComments = "f69f8452-a1be-45e8-8c71-a1fcc6a0dbcd",
  // AnswerToVotes is the edgeType for the answer to votes edge.
  AnswerToVotes = "c60240be-8b1e-4987-a87e-0934a6d3f29a",
  // AnswerVoteToVoters is the edgeType for the answerVote to voters edge.
  AnswerVoteToVoters = "1b97dcf2-04fc-4a1c-9625-9cbd090be224",
  // QuestionCommentToAuthors is the edgeType for the questionComment to authors edge.
  QuestionCommentToAuthors = "1daa71ae-916d-45d5-b86a-91de3dc33356",
  // QuestionPrivateNoteToAuthors is the edgeType for the questionPrivateNote to authors edge.
  QuestionPrivateNoteToAuthors = "33c7d9f9-c700-466b-b278-e40b887f7ac4",
  // QuestionToAnswers is the edgeType for the question to answers edge.
  QuestionToAnswers = "69eb1cb3-9fa7-437b-8474-21092a525de7",
  // QuestionToAuthors is the edgeType for the question to authors edge.
  QuestionToAuthors = "dbdae75e-1072-438e-8713-4f4284b289ad",
  // QuestionToComments is the edgeType for the question to comments edge.
  QuestionToComments = "1f939a84-c765-4168-a6d1-ac9deea9d34e",
  // QuestionToPrivateNotes is the edgeType for the question to privatenotes edge.
  QuestionToPrivateNotes = "ad37d17b-4319-4192-8a59-6499dd870edb",
  // QuestionToVotes is the edgeType for the question to votes edge.
  QuestionToVotes = "67432296-9c50-4b5b-afe0-67d28c6e7776",
  // QuestionVoteToVoters is the edgeType for the questionVote to voters edge.
  QuestionVoteToVoters = "ee449750-58df-4a33-a692-d8bf90e70a9d",
  // UserToAnswersVoted is the edgeType for the user to answersvoted edge.
  UserToAnswersVoted = "7293e3fd-0ddd-424c-a740-27392e885d7e",
  // UserToAuthenticationDetails is the edgeType for the user to authenticationdetails edge.
  UserToAuthenticationDetails = "76806fdf-2a89-4c5f-947b-1bd9dad8b03d",
  // UserToAuthorToAuthoredAnswerComments is the edgeType for the user to authortoauthoredanswercomments edge.
  UserToAuthorToAuthoredAnswerComments = "21319a5d-1678-4a97-8d9f-e8af198504b2",
  // UserToAuthorToAuthoredAnswers is the edgeType for the user to authortoauthoredanswers edge.
  UserToAuthorToAuthoredAnswers = "334a0a65-f4bf-4119-b1b8-7e60e86c5374",
  // UserToAuthorToAuthoredQuestionComments is the edgeType for the user to authortoauthoredquestioncomments edge.
  UserToAuthorToAuthoredQuestionComments = "1888c833-ad80-4f06-846b-96fab877b50b",
  // UserToAuthorToAuthoredQuestions is the edgeType for the user to authortoauthoredquestions edge.
  UserToAuthorToAuthoredQuestions = "f5f98bc4-94ed-4b3d-88b5-628992440185",
  // UserToAuthoredAnswerComments is the edgeType for the user to authoredanswercomments edge.
  UserToAuthoredAnswerComments = "2bd913d5-a2cb-485b-9563-4c2e447b99b2",
  // UserToAuthoredAnswers is the edgeType for the user to authoredanswers edge.
  UserToAuthoredAnswers = "b39d9e6f-2249-4c6c-b4b3-e8c14430b60e",
  // UserToAuthoredQuestionComments is the edgeType for the user to authoredquestioncomments edge.
  UserToAuthoredQuestionComments = "641dd0e0-ca29-44cb-8c78-21c6a9962609",
  // UserToAuthoredQuestions is the edgeType for the user to authoredquestions edge.
  UserToAuthoredQuestions = "eb398e63-df78-40d2-9e86-50a3a788c88f",
  // UserToQuestionPrivateNotes is the edgeType for the user to questionprivatenotes edge.
  UserToQuestionPrivateNotes = "5da8f466-0498-42ed-9f0f-9138223793b9",
  // UserToQuestionsVoted is the edgeType for the user to questionsvoted edge.
  UserToQuestionsVoted = "92e68df1-d754-43dd-8e0d-6016f6caaba9",
  // UserToUserQuestionPrivateNotes is the edgeType for the user to userquestionprivatenotes edge.
  UserToUserQuestionPrivateNotes = "fd476c64-01c5-44b3-859b-a15dc450d1f9",
  // UserToVoterToAnswersVoted is the edgeType for the user to votertoanswersvoted edge.
  UserToVoterToAnswersVoted = "e11767f0-385f-40d0-83de-4100463fd65a",
  // UserToVoterToQuestionsVoted is the edgeType for the user to votertoquestionsvoted edge.
  UserToVoterToQuestionsVoted = "f0d2fac2-6682-4150-aa90-b42749eae9d0",
}

export function getEdgeTypeValues() {
  return [
    EdgeType.AnswerCommentToAuthors,
    EdgeType.AnswerToAuthors,
    EdgeType.AnswerToComments,
    EdgeType.AnswerToVotes,
    EdgeType.AnswerVoteToVoters,
    EdgeType.QuestionCommentToAuthors,
    EdgeType.QuestionPrivateNoteToAuthors,
    EdgeType.QuestionToAnswers,
    EdgeType.QuestionToAuthors,
    EdgeType.QuestionToComments,
    EdgeType.QuestionToPrivateNotes,
    EdgeType.QuestionToVotes,
    EdgeType.QuestionVoteToVoters,
    EdgeType.UserToAnswersVoted,
    EdgeType.UserToAuthenticationDetails,
    EdgeType.UserToAuthorToAuthoredAnswerComments,
    EdgeType.UserToAuthorToAuthoredAnswers,
    EdgeType.UserToAuthorToAuthoredQuestionComments,
    EdgeType.UserToAuthorToAuthoredQuestions,
    EdgeType.UserToAuthoredAnswerComments,
    EdgeType.UserToAuthoredAnswers,
    EdgeType.UserToAuthoredQuestionComments,
    EdgeType.UserToAuthoredQuestions,
    EdgeType.UserToQuestionPrivateNotes,
    EdgeType.UserToQuestionsVoted,
    EdgeType.UserToUserQuestionPrivateNotes,
    EdgeType.UserToVoterToAnswersVoted,
    EdgeType.UserToVoterToQuestionsVoted,
  ];
}
